#!/bin/sh

NAME="$1"
TIME="$2"

if [ "$NAME" != "" ]; then
	MAC=$(cat /etc/config/dhcp |grep -A 1 "$NAME" | grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" |awk '{printf $0}')
	if [ "$MAC" != "" ]; then
		uci add firewall rule
		uci set firewall.@rule[-1].src='lan'
		uci set firewall.@rule[-1].dest='wan' 
		uci set firewall.@rule[-1].proto='all'
		uci set firewall.@rule[-1].target='REJECT'
		uci set firewall.@rule[-1].src_mac="$MAC"
		if [ "$TIME" == "time" ]; then
			uci set firewall.@rule[-1].name="Время блокировки ${NAME}"
			uci set firewall.@rule[-1].start_time='23:00'
			uci set firewall.@rule[-1].stop_time='08:00'
			uci set firewall.@rule[-1].weekdays='пон вт ср чт пт сб вс'
		else
			uci set firewall.@rule[-1].name="Блокировка Телеграм ${NAME}"
		fi
		uci reorder firewall.@rule[-1]=1 
		uci commit firewall &> /dev/null
		/etc/init.d/firewall restart &> /dev/null
		if [ "$TIME" == "time" ]; then
			echo "Новое правило между 23:00 и 8:00 для ${NAME} успешно создано !"
		else
			echo "Новое правило для ${NAME} успешно создано !"
		fi
		exit 0
	fi
fi
echo "Ошибка создания нового правила ${NAME} !"
exit 1
